version: "3.2"
services:
  db: 
    env_file:
      - ./env/dev.env
    image: "postgres"
    ports:
      - "5432:5432"
    restart: "always"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - ./env/dev.env
    depends_on:
      - db
    command: bash -c "bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"