default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch("POSTGRES_DB_NAME") %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") %>

  # The password associated with the postgres role (username).
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  host: <%= ENV.fetch("POSTGRES_HOST") %>

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  port: <%= ENV.fetch("POSTGRES_PORT") %>

development:
  <<: *default
  database: itunes_albums_development

test:
  <<: *default
  database: itunes_albums_test

production:
  <<: *default
  database: itunes_albums_production
  username: itunes_albums
  password: <%= ENV["ITUNES_ALBUMS_DATABASE_PASSWORD"] %>
